In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("session4_dummy_students_data.csv")

print(df.head())
print(df.info())
print(df.dtypes)
print("Shape:",df.shape)
print("Columns:", df.columns.tolist())

   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69   
1         102   Diya   16    Delhi    91       88       94   
2         103  Kabir   17  Mathura    55       61       58   
3         104  Meera   16    Noida    72       79       81   
4         105  Rohan   17   Mumbai    40       52       47   

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9   
1                  96                    11                     10   
2                  75                     5                      6   
3                  89                     7                      8   
4                  68                     3                      5   

   final_project_score  
0                   82  
1                   93  
2                   60  
3                   78  
4                   45  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 ent

In [ ]:
#numpy completion

#parameters

def calculate_average(values):
    if len(values)==0:
        return None #Ye nahi krenge to Zero Divison Error aayega
    return sum(values)/len(values)
scores = [77,90,87,45]
result = calculate_average(scores)
print(result)


74.75


In [ ]:
#numpy Arrays are Homogeneous, can have only one type of data. Agar string ke saath integer diya aur string mein bhi integer hai to direct error nhi dega, jaha tak hai sudharne ki koshish krega
math_scores = df["math"].to_numpy()

print(math_scores)
print("Mean of the scores: ", math_scores.mean())
print("Minimum: ", math_scores.min())
print("Maximum: ", math_scores.max())
print("Total: ", math_scores.sum())

science_scores = df["science"].to_numpy()
print("Maximum: ", science_scores.max())
print("Minimum: ", science_scores.min())
print("Mean of the scores: ", science_scores.mean())
print("Total: ", science_scores.sum())
print("Median", np.median(science_scores))

english_scores = df["english"].to_numpy()
print("Maximum: ", english_scores.max())
print("Minimum: ", english_scores.min())
print("Mean of the scores: ", english_scores.mean())

print("Total: ", english_scores.sum())


[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
Mean of the scores:  69.5
Minimum:  35
Maximum:  95
Total:  1390
Maximum:  93
Minimum:  45
Mean of the scores:  72.35
Total:  1447
Median 74.5
Maximum:  96
Minimum:  42
Mean of the scores:  72.2
Total:  1444


In [ ]:
#InSight Creation
print('Math Insights')
print(math_scores > 75) #Prints True and False
print(math_scores[math_scores>75]) #Filters out the values according to the condition
print("Count of scores above 75:", (math_scores>75).sum())

Math Insights
[ True  True False False False  True False  True False  True False False
 False  True False  True False  True False  True]
[78 91 88 95 83 89 92 80 77]
Count of scores above 75: 9


In [ ]:
#Ques: Convert The English Column into numpy , create mean, lowest, hightest, print number of scores greater than or equal to 80
english_scores = df["english"].to_numpy()
print("Maximum: ", english_scores.max())
print("Minimum: ", english_scores.min())
print("Mean of the scores: ", english_scores.mean())
print(english_scores[english_scores>=80])
print("Count of scores 80 or above:  ", (english_scores>=80).sum())

Maximum:  96
Minimum:  42
Mean of the scores:  72.2
[94 81 90 89 85 91 96 83 80]
Count of scores 80 or above:   9


In [ ]:
print(df.info()) #Helps in inspection
print(df.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   student_id             20 non-null     int64 
 1   name                   20 non-null     object
 2   age                    20 non-null     int64 
 3   city                   20 non-null     object
 4   math                   20 non-null     int64 
 5   science                20 non-null     int64 
 6   english                20 non-null     int64 
 7   attendance_percent     20 non-null     int64 
 8   study_hours_per_week   20 non-null     int64 
 9   assignments_submitted  20 non-null     int64 
 10  final_project_score    20 non-null     int64 
dtypes: int64(9), object(2)
memory usage: 1.8+ KB
None
student_id                int64
name                     object
age                       int64
city                     object
math                      int64
science            

In [ ]:
#Column Cleaning: Changes columns names only, not data.
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)
print(df.columns.tolist())

['student_id', 'name', 'age', 'city', 'math', 'science', 'english', 'attendance_percent', 'study_hours_per_week', 'assignments_submitted', 'final_project_score']


In [ ]:
df["student_id"] = df["student_id"].astype("string")
df["city"] = df["city"].astype("category")

In [ ]:
#MISSING VALUES

missing_demo = df.copy()

missing_demo.loc[2, "science"] = np.nan
missing_demo.loc[8, "attendance_percent"] = np.nan
missing_demo.loc[14, "city"] = None

print(missing_demo.isna().sum())

student_id               0
name                     0
age                      0
city                     1
math                     0
science                  1
english                  0
attendance_percent       1
study_hours_per_week     0
assignments_submitted    0
final_project_score      0
dtype: int64


In [ ]:
science_median = missing_demo["science"].median()
attendance_median = missing_demo["attendance_percent"].median()
city_mode = missing_demo["city"].mode(0)

missing_demo["science"] = missing_demo["science"].fillna(science_median)
missing_demo["attendance"] = missing_demo["attendance_percent"].fillna(attendance_median)
missing_demo["city"] = missing_demo["city"].fillna(city_mode)

In [ ]:
#Create a copy named practice_df. Make the math value in the row 0 missing. Fill the missing math value with math median
# Print the missing Value
practice_df = df.copy()
practice_df.loc[0,"math"] = np.nan
math_median = practice_df["math"].median()
practice_df["math"] = practice_df["math"].fillna(math_median)
print("Filled value for row 0:", practice_df.loc[0, "math"] )
print(math_median)

Filled value for row 0: 72.0
72.0


In [ ]:
#Averages and some basic Summaries
# Deroving a new column (feature curation) for each student we will calculate their subject averages
df["average_score"] = (
    df[["math","science","english"]]
    .mean(axis=1)
    .round(2)
)
print(df[["name","math","science","english","average_score"]].head())
print("Class average:", df["average_score"].mean())
print("Lowest average:", df["average_score"].min())
print("Highest average:", df["average_score"].max())
print("Students:",df["student_id"].count())

print(df["average_score"].describe()) #Generates a quick statistical summary of a DataFrame

    name  math  science  english  average_score
0  Aarav    78       84       69          77.00
1   Diya    91       88       94          91.00
2  Kabir    55       61       58          58.00
3  Meera    72       79       81          77.33
4  Rohan    40       52       47          46.33
Class average: 71.35000000000001
Lowest average: 40.67
Highest average: 92.67
Students: 20
count    20.000000
mean     71.350000
std      16.753219
min      40.670000
25%      57.832500
50%      76.835000
75%      84.170000
max      92.670000
Name: average_score, dtype: float64


In [ ]:
#Count mean, min, max
#idxmax() = returns the index label of the maximum value in a Series or along a specified axis of a DataFrame
#loc = a property used to select, filter, and modify data in a DataFrame using label-based indexing
top_student = df.loc[df["average_score"].idxmax(),["name", "average_score"] ]
print(top_student)

low_attendance = df[df["attendance_percent"]<75]
print(low_attendance[["name","attendance_percent","average_score"]])

name              Riya
average_score    92.67
Name: 15, dtype: object
      name  attendance_percent  average_score
4    Rohan                  68          46.33
8   Vivaan                  71          52.00
12     Dev                  62          40.67
18    Yash                  66          46.00


In [ ]:
#HomeWork:
#Group the data by:
#same city
#top 25 np.percentile
#Based on these groups, identify some insights
print(df["city"]) #Used this to check all the available city catgories
#Grouping by city
#Finding mean average_score for each city respectivrly to find which cities perform better and which is the best overall
city_performance = df.groupby("city")['average_score'].mean().reset_index()
#reset_index():Resets the index of the DataFrame, and uses the default one instead.
city_performance = city_performance.sort_values(by='average_score', ascending=False)
print('Average Scores Citywise')
print(city_performance)
#Calculating the top 25 percentile
#The top 25 students should be the ones who are 75 percentile achievers
threshold_75 = np.percentile(df['average_score'].dropna(), 75)
#Creating a new dataframe for students who satisfy the threshold
top_25 = df[df['average_score']>= threshold_75]
print('Top 25% Threshold Score:', threshold_75)
print(top_25[['name','city','average_score']])
#Comibining both grouping conditions to Derive Insights
top_student_info = top_25.groupby('city').size().reset_index(name="number_of_top_students")
#Grouped top_25 df with city to know about the smartest kids
top_student_info = top_student_info.sort_values(by='number_of_top_students', ascending = False)

print('City Distribution of Top 25% Students')
print(top_student_info)

0      Mumbai
1       Delhi
2     Mathura
3       Noida
4      Mumbai
5       Delhi
6     Mathura
7       Noida
8      Mumbai
9       Delhi
10    Mathura
11      Noida
12     Mumbai
13      Delhi
14    Mathura
15      Noida
16     Mumbai
17      Delhi
18    Mathura
19      Noida
Name: city, dtype: category
Categories (4, object): ['Delhi', 'Mathura', 'Mumbai', 'Noida']
Average Scores Citywise
      city  average_score
0    Delhi         86.800
3    Noida         83.334
1  Mathura         59.066
2   Mumbai         56.200
Top 25% Threshold Score: 84.17
      name   city  average_score
1     Diya  Delhi          91.00
5     Sara  Delhi          90.33
7   Ananya  Noida          92.00
13   Priya  Delhi          88.67
15    Riya  Noida          92.67
City Distribution of Top 25% Students
      city  number_of_top_students
0    Delhi                       3
3    Noida                       2
1  Mathura                       0
2   Mumbai                       0


/tmp/ipykernel_1871/1786769171.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  city_performance = df.groupby("city")['average_score'].mean().reset_index()
/tmp/ipykernel_1871/1786769171.py:22: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  top_student_info = top_25.groupby('city').size().reset_index(name="number_of_top_students")


Based on the calculations, it was observed that majority of top performing students are from Delhi and Noida. It was also observed that city averages of Mathura and Mumbai were way lesser than Delhi and Noida.